name: "Tell a Joke Action"
author: "Arnab Sau"
description: "A GitHub Action that tells a random programming joke."
branding:
  color: blue
  icon: activity
runs:
  using: "docker"
  image: "Dockerfile"